apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: ingress-nginx
spec:
  targetGroupARN: {{ .Values.targetGroupARN | quote }}
  targetType: ip
  serviceRef:
    name: {{ .Values.serviceName | quote }}
    port: {{ .Values.servicePort }}
